=== rezajebeli97/Advanced-Search-Engine/resources/corpora/hamshahri/1996/hamshahri.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT HAMSHAHRI2 (COPYRIGHT, DOC+)>
<!ELEMENT DOC (DOCID, DOCNO, ORIGINALFILE, ISSUE, DATE, CAT, CAT, TITLE, TEXT)>
<!ELEMENT DOCID (#PCDATA)>
<!ELEMENT DOCNO (#PCDATA)>
<!ELEMENT ORIGINALFILE (#PCDATA)>
<!ELEMENT ISSUE (#PCDATA)>
<!ELEMENT DATE (#PCDATA)>
<!ATTLIST DATE calender (Persian | Western) #REQUIRED>
<!ELEMENT CAT (#PCDATA)>
<!ATTLIST CAT xml:lang (en | fa) #REQUIRED>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT TEXT (#PCDATA)>

=== rezajebeli97/Advanced-Search-Engine/resources/corpora/hamshahri/1996/HAM2-960623.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE HAMSHAHRI2 SYSTEM "hamshahri.dtd">

<HAMSHAHRI2>
<DOC>
<DOCID>HAM2-750403-001</DOCID>
<DOCNO>HAM2-750403-001</DOCNO>
<ORIGINALFILE>/1375/750403/adabh79.htm</ORIGINALFILE>
<ISSUE>يكشنبه 3 تير 1375، 23 ژوئن 1996، سال چهارم، شماره 1000</ISSUE>
<DATE calender="Western">1996-06-23</DATE>
<DATE calender="Persian">1375/04/03</DATE>
<CAT xml:lang="fa">ادب و هنر</CAT>
<CAT xml:lang="en">Literature and Art</CAT>
<TITLE>
<![CDATA[گفتگو با مسعود كيميايي كارگردان
فيلم ضيافت دعوت به مهرورزي و سازندگي]]>
</TITLE>
<TEXT>
<![CDATA[o در اجراي ضيافت حالا، مناسبات تغيير كرده اند، مهرورزي، يگانه تر
است آواز مهرورزي و سازندگي است
o يك جامعه مدعي رو به رشد، بر زمينه انتقادي صحيح حركت سازنده تري
خواهد داشت
حرف اصلي فيلم ضيافت چيست و چگونه اين حرف پرداخت شده است؟]]>
</TEXT>
</DOC>
</HAMSHAHRI2>
